---

- name: prometheus jmx | add kafka user to correct jmx exporter user
  user:
    name: "{{ kafka_var.user }}"
    groups: "{{ jmx_exporter_group }}"
    append: yes

- name: prometheus jmx | configuration file
  become: yes
  copy:
    dest: "{{ prometheus_jmx_config }}"
    src: jmx-kafka-config.yml
    owner: "{{ kafka_var.user }}"
    group: "{{ kafka_var.group }}"
    mode: 0644

- name: delegated | create prometheus system group
  group:
    name: prometheus
    system: true
    state: present
  delegate_to: "{{ item }}"
  with_inventory_hostnames:
    - prometheus

- name: delegated | create prometheus system user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false
  delegate_to: "{{ item }}"
  with_inventory_hostnames:
    - prometheus

- name: delegated | create file_sd for service discovery configs
  file:
    dest: "{{ prometheus_config_dir }}/file_sd"
    state: directory
    owner: root
    group: prometheus
    mode: 0750
  delegate_to: "{{ item }}"
  with_inventory_hostnames:
    - prometheus

- name: delegated | copy file_sd_config to prometheus hosts
  template:
    dest: "{{ prometheus_config_dir }}/file_sd/kafka-jmx-{{ inventory_hostname }}.yml"
    src: file_sd_config.yml.j2
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{ item }}"
  notify: restart prometheus
  with_inventory_hostnames:
    - prometheus
