---
# Ansible playbook that deploys applications on Kubernetes after cluster creation

- hosts: all
  tasks: [ ]  

- hosts: deployments
  become: true
  become_method: sudo
  roles:
    - deployments
