---
- name: Add RabbitMQ policies
  rabbitmq_policy:
    name: "{{ item.name }}"
    pattern: "{{ item.pattern }}"
    tags: "{{ item.definitions }}"
    state: present
  loop: "{{ rabbitmq_policies }}"
  when: groups['rabbitmq'][0] == inventory_hostname
