---
apiVersion: v1
kind: Service
metadata:
  name: epiphany-examples-api-svc
  labels:
    version: 1.0.0
spec:
  selector:
    app: epiphany-examples-api
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: https-port
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 31443
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: epiphany-examples-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: epiphany-examples-api
    spec:
      containers:
      - name: epiphany-examples-api
        image: epiphanyplatform/examples-queue-api:0.2.0
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        # Parameters that defines model size to publish/consume
        - name: MODELS_NUMBER # Number of models in on message
          value: "1"
        - name: PARAM_NUMBER # Number of parameters in one model                     
          value: "5"
        - name: WAIT_TIME # Wait time in ms after producing/receiving message - mimic calculations                     
          value: "10"
        # ---
        - name: USE_QUEUE # Which queue system to use, allowed values: Kafka, RabbitMQ
          value: "Kafka"
        - name: TOPIC_NAME # Name of the topic for publishing/consuming messages
          value: "test-topic"
        - name: PRODUCE_INFINITELY # For worker applications (not REST API)
          value: "0"
        # RabbitMQ specific - required if USE_QUEUE == RabbitMQ
        - name: RABBITMQ_HOSTNAME
          value: "10.1.1.9"  # Put here IP private IP/hostname RabbitMQ instance - if RabbitMQ was installed in cluster, take one of the nodes IP
        - name: RABBITMQ_DURABLE
          value: "0"
        - name: RABBITMQ_PORT 
          value: "30672"
        - name: RABBITMQ_USER
          value: "your-rabbitmq-user"
        - name: RABBITMQ_PASSWORD
          value: "your-rabbitmq-password"
        # ---
        # Kafka specific - required if USE_QUEUE == Kafka
        - name: KAFKA_ENDPOINT
          value: "10.1.1.10:9092" # Put here IP private IP/hostname and port of your Kafka instance
        - name: KAFKA_GROUP_ID
          value: "testconsumergroup"
        - name: KAFKA_SESSION_TIMEOUT_MS
          value: "10000"
        # ---
        # Kubernetes specific - no need to change
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        # ---
