---
- name: create node_exporter system group
  group:
    name: node_exporter
    system: true
    state: present

- name: create node_exporter system user
  user:
    name: node_exporter
    system: true
    shell: "/usr/sbin/nologin"
    group: node_exporter
    createhome: false

- name: download node_exporter binary to local folder
  become: false
  get_url:
    url: "{{ url }}"
    dest: "{{ prometheus_node_exporter_download_path }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost

- name: unpack node_exporter binary
  become: false
  unarchive:
    src: "{{ prometheus_node_exporter_download_path }}"
    dest: "{{ prometheus_node_exporter_download_dir }}"
    creates: "{{ prometheus_node_exporter_download_dir }}/{{ prometheus_node_exporter_release_name }}/node_exporter"
  delegate_to: localhost
  check_mode: false

- name: create /opt/node_exporter directories
  become: yes
  file:
    path: "{{ item }}"
    recurse: yes
    owner: root
    group: "node_exporter"
    mode: 0750
    state: directory
  with_items:
  - /opt/node_exporter

- name: propagate node_exporter binaries
  copy:
    src: "{{ prometheus_node_exporter_download_dir }}/{{ prometheus_node_exporter_release_name }}/node_exporter"
    dest: "/opt/node_exporter/node_exporter"
    mode: 0755
    owner: root
    group: node_exporter
  check_mode: false
  notify:
    - restart prometheus-node-exporter

- name: install node_exporter service to systemd
  template:
    src: prometheus-node-exporter.service.j2
    dest: /etc/systemd/system/prometheus-node-exporter.service
    owner: root
    group: root
    mode: 0644

- name: configure systemd to use node_exporter service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: prometheus-node-exporter.service

- name: copy file_sd_config to prometheus hosts
  template:
    dest: "{{ prometheus_config_dir }}/file_sd/node-{{ inventory_hostname }}.yml"
    src: file_sd_config.yml.j2
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{ item }}"
  with_inventory_hostnames:
    - prometheus
  notify: restart prometheus on remote servers
