---

- name: create haproxy_exporter system group
  group:
    name: haproxy_exporter
    system: true
    state: present

- name: create haproxy_exporter system user
  user:
    name: haproxy_exporter
    system: true
    shell: "/usr/sbin/nologin"
    group: haproxy_exporter
    createhome: false

- name: download haproxy_exporter binary to folder
  become: false
  get_url:
    url: "{{ prometheus_haproxy_exporter_url_download }}"
    dest: "{{ prometheus_haproxy_exporter_download_dir }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  

- name: unpack haproxy_exporter binary
  become: false
  unarchive:
    src: "{{ prometheus_haproxy_exporter_download_dir }}/haproxy_exporter-0.9.0.linux-amd64.tar.gz"
    dest: "{{ prometheus_haproxy_exporter_extract_dir }}" 
    remote_src: yes
  check_mode: false

- name: create /opt/haproxy_exporter directories
  become: yes
  file:
    path: "{{ item }}"
    recurse: yes
    owner: root
    group: haproxy_exporter
    mode: 0750
    state: directory
  with_items:
  - /opt/haproxy_exporter

- name: copy haproxy_exporter binary
  copy:
    src: "{{ prometheus_haproxy_exporter_extract_dir }}/haproxy_exporter-0.9.0.linux-amd64/haproxy_exporter" 
    dest: "/opt/haproxy_exporter/haproxy_exporter"
    owner: root
    group: haproxy_exporter
    mode: 0755
    remote_src: yes

- name: install haproxy_exporter service to systemd
  template:
    src: prometheus-haproxy-exporter.service.j2
    dest: /etc/systemd/system/prometheus-haproxy-exporter.service
    owner: root
    group: root
    mode: 0644

- name: configure systemd to use prometheus-haproxy-exporter service
  systemd:
    enabled: yes
    state: started
    name: prometheus-haproxy-exporter
    daemon_reload: yes

- name: copy file_sd_haproxy_config to prometheus hosts
  template:
    dest: "{{ prometheus_config_dir }}/file_sd/haproxy-{{ inventory_hostname }}.yml"
    src: file_sd_haproxy_config.yml.j2
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{ item }}"
  with_inventory_hostnames:
    - prometheus
